### PR TITLE
Added support for Serialization by System.Text.Json

### PR DESCRIPTION
**Pull request by RyadaProductions**
PR for issue #12

I changed the fields on the data objects to properties as well as changing the JObject into a normal object.
I am open for discussion on the JObject to object change, as it isn't the most graceful way but it doesn't break the tests. Nor does it break the Json serialization.

### CODE REVIEW

**Comment by RyadaProductions** [comment]
The checks are apparently failing because of an invalid API key on AppVeyor.

**Comment by RyadaProductions** [comment]
@MingweiSamuel appologies for pinging you but would you be so kind as to take a look at this?

**Comment by MingweiSamuel** [comment]
Yes thanks for your patience, been having some power issues out here in Berkeley

**Comment by MingweiSamuel** [comment]
Does this actually work to rid of dependencies on `Newtonsoft.Json`, since the `using`s are still there?

**Comment by RyadaProductions** [comment]
The intention wasn't to get rid of `Newtonsoft.Json` entirely. 
The intention was that people would be able to use the library in their own ASP.NET webapi project without having to implement the `Newtonsoft.Json` library as the serialization middleware.

But if that would be preferred i can change the PR to replace `Newtonsoft.Json` with `System.Text.Json`

**Comment by MingweiSamuel** [comment]
While messing around with CI it seems I accidentally made a nightly build with your changes, so you can use that while I decide what to do https://www.nuget.org/packages/MingweiSamuel.Camille/2.2.3-nightly-2019-10-08-e3bfd086b0  
I'm not sure exactly how the patch will handle the fields `created_at` and `updated_at` since they contain underscores, so keep that in mind if you hit LolStatusV3.

**Comment by MingweiSamuel** [comment]
Merged d342f0e2af8ac14fde3644769a9c412e19f757a8
Thanks for the PR!

**Pull request closed without merging**
