### PR TITLE
Added Emerald and Cherry(2v2v2v2) Queue Type. Fixed error that happen…

### PR DESCRIPTION
**Pull request by luisgon-dev**
…s when a player has a cherry rank. (tier and a couple others aren't included in the response)

### CODE REVIEW

**Comment by Kronicvbr33z3** [comment]
Related to Issue #99

**Comment by luisgon-dev** [comment]
Was running into error in my own project for this, not sure if this is the right fix but it's working for me now.

**Comment by luisgon-dev** [comment]
[/lol/league/v4/entries/by-summoner/{encryptedSummonerId}](https://developer.riotgames.com/apis#league-v4/GET_getLeagueEntriesForSummoner)] endpoint doesn't return consistent fields with the new game mode ranked. No tier, rank, or leagueid.

**Comment by Alcamoru** [comment]
I agree, my project can't run.

**Comment by selmaohneh** [comment]
@MingweiSamuel we really need an update on the failing CI and this PR please. Some projects are currently broken due to the lack of the nightly builds.

**Comment by MingweiSamuel** [comment]
0b07b9417273b141223613bedb5852a2b6ebf887

**Comment by MingweiSamuel** [comment]
@selmaohneh 

>@MingweiSamuel we really need an update on the failing CI and this PR please. Some projects are currently broken due to the lack of the nightly builds.

New nightly is now released
https://www.nuget.org/packages/Camille.RiotGames/3.0.0-nightly-2023-08-27-1f7c420fef

**Pull request closed without merging**
