### PR TITLE
Enable Dependabot

### PR DESCRIPTION
**Pull request by mikaeldui**
[To keep dependencies up-to-date.](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically)

### CODE REVIEW

**Comment by MingweiSamuel** [comment]
So as a library in general we'd want to support the widest range of versions as possible. Looking at https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges , something like `<PackageReference Include="Newtonsoft.Json" Version="9.0.1" />` actually means `Newtonsoft.Json >= 9.0.1` , and this even includes major versions which is a bit strange. But overall a lower version means a wider range...

Interestingly, in a test project when I included `Camille.RiotGames` as a dependency it did end up pulling `Newtonsoft.Json = 9.0.1`. But then when I separately installed `Newtonsoft.Json = 13.0.1` it did upgrade to that version without any build or runtime conflicts, and inspecting the bin did show just the v13 dll.

I'm not really sure what the best practice is with c#/nuget.

Of course, for the test projects and the node srcgen, those can be kept up to latest since they're internal.

**Comment by MingweiSamuel** [comment]
Also once .NET Framework 4.5.2/4.6/4.6.1 support ends we won't need Newtonsoft.JSON anymore. (.NET Framework 4.6.1 is the earliest version that can run System.Text.Json)

**Comment by mikaeldui** [comment]
Related article: https://docs.microsoft.com/en-us/nuget/concepts/security-best-practices

**Comment by mikaeldui** [comment]
@MingweiSamuel what about setting the NuGet package references as [`PrivateAssets="all"`](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets)? If someone wants to use `Newtonsoft.Json` in their project for something else they'd have to install it themselves and would probably install the latest version.

**Pull request merged**
